//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfetKayit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afet_turDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Afet_turDB()
        {
            this.AfetDB = new HashSet<AfetDB>();
        }
    
        public int afet_tur_id { get; set; }
        public string afet_tur_adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfetDB> AfetDB { get; set; }
    }
}
