//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfetKayit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilceler
    {
        public int ilce_id { get; set; }
        public string ilce { get; set; }
        public int il_id { get; set; }
    
        public virtual iller iller { get; set; }
    }
}
