//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfetKayit1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class onayDB
    {
        public int onay_id { get; set; }
        public byte[] onay_tur { get; set; }
    }
}
